### PR TITLE
Bufferization for pipes

### PR DESCRIPTION
**Pull request by huumanoid**
After previous pull request #5  related to issue #4 socks data still goes to pipe, this is unwanted behavior.
This pull request fixes such behavior by adding bufferization in [proxysocket.write](https://github.com/krisives/proxysocket/blob/3e59b11292aa33418490b2a586d45429e5f79a28/proxysocket.js#L345-L352) manner.

### CODE REVIEW

**Comment by krisives** [comment]
I will get this merged shortly, I want to test it first.

**Comment by Miserlou** [comment]
I thinkkkkkk this is getting closer, but I'm still not able to use this seamlessly. 

Before this patch, I was seeing extraneous <Buffer 05 00 00 > bytes in my streams, (which I assume were the SOCKS headers, so I was trying to manually ignore those bytes at the application layer). With this patch, I'm not seeing them anymore, but my sockets are still closing too early. Progress though?

**Comment by Miserlou** [comment]
Still getting incorrect values with the piped sockets. It's supposed to be 

<Buffer 00 00 00 9f>

and instead I get something like

<Buffer 6e 30 72 63>

Is there anyway that the values could be modified, or that the zeroes are being truncated? I'm having my proxy echo all the buffers to console, and I don't see the 6e 30 72 63 stream anywhere.

**Comment by HuuMaNoID** [comment]
Hello @Miserlou and thank you for your feedback.
I've tested pipes.
* Launched socks proxy on my local machine
* Launched echo server on my local machine.
* Started client, that
  * creates proxysocket
  * pipes it to a file named *test-file*
  * connects to echo server
  * generates random m - number of sending chunks.
  * m times:
    * generates n random bytes (where  is random) and sends them.
    * also, writes sent bytes to *control-file*

I've run this test for 1000 times

It seems like pipe is ok. For all n in 1..1000
```shell
cmp test-file-n control-file-n
```
returns OK.

But, while writing this test, i have been receiving suspicious bytes. It was caused by encoding inconsistency. Default encoding of my writeable stream for *test-file* wasn't set to binary, and encoding , so instead of `a1 00 ce ef` i had been receiving `c2 a1 00 c3 8e c3...`.
May be this is your case? What encoding your data is?

**Comment by Miserlou** [comment]
@HuuMaNoID - thanks for your feedback!

I suspected that socket encoding could be involved, but my early experiments didn't yield anything, although I think there's more I could do there now that I've read the docs a bit more. Will report back.

Could you do me a big favor and share your proxy test set-up in a new repo so that I could use it for my own diagnostic purposes? Perhaps this has something to do with my node version or operating system or something like that. If I could confirm that your working set up works on my system, then at least I can eliminate some of those as error sources.

Does socket encoding actually affect the _contents_ of the socket, that is to say the bytes sent over the wire, or is it just the way that the bytes are displayed when echoed to the console?

**Comment by Miserlou** [comment]
Another issue is that for my purposes I require many simultaneous connections through the proxy, so I'd like to try to modify your test environment to see if I can get the errors by running it in parallel rather than sequentially.

**Comment by HuuMaNoID** [comment]
Here it is, you are welcome: https://github.com/HuuMaNoID/proxysocket-test
Check out parallel-tests.

Encodings may affect contents of buffers.
Look at this:
```js
var socket = getProxySocketSomehow();
socket.setEncoding('binary');

var writeable = getWriteableStreamSomehow();
writeable.setEncoding('utf8');//actually, it's default encoding!

socket.pipe(writeable);
```
In this case, socket, receiving chunk of data, decodes it as 'binary' string. Then, decoded string passed to writeable stream and treated as utf8 string.
So, following data transformations take place:
```js
// let's say, server sent packet with bytes [0xD0, 0xBF]
// [0xD0, 0xBF] - utf8 representation of russian letter 'п'
// but i don't mean server sent russian letter. 
// Just let's say server sent such bytes, no matter what they mean.
var packet = new Buffer('п', 'utf8');

// socket receives packet and decodes it like a 'binary' string
var bin = packet.toString('binary');

// writeable takes bin, piped by socket, treates it like utf8 string
// and writes to file/whatever.
var written = new Buffer(bin, 'utf8'); 
// Guess what? \
// console.log(written) === [0xC3, 0x90, 0xC2, 0xBF]
```
You can learn more in `lib/stream.js` `lib/_stream_readable.js` of node library.

**Comment by HuuMaNoID** [comment]
Also, i extremely suggest to set proxysocket's encoding to 'binary'. This caused by proxysocket's bug, which i'm going to fix when this pull request will be closed.

**Comment by Miserlou** [comment]
Excellent! Thank you so much for sharing this! I haven't had a chance to try it out yet but I'm about to, will report back with my findings.

**Comment by Miserlou** [comment]
Okay, I have the tests working, but I'm actually not quite sure what the expected output should be!

For both the sync and parallel tests, I get this output:

``
~/Projects/proxysocket-test $ node pipes/sync-test.js 
2/182
3/182
[ .. ]
suite: 1, test and control files have different length. test has 8097 control has 8085
suite: 2, test and control files have different length. test has 25520 control has 25508
suite: 3, test and control files have different length. test has 2768 control has 2756
[ .. ]
checks passed successfully
``

Is this the "expected" behavior? To me that seems like it should be a test failure, given that the test and control samples don't match each other. (This is using a [simple-socks](https://github.com/brozeph/simple-socks/tree/master/examples) as an SOCKS5 server.)

Is that what happens when you run the same tests?

**Comment by Miserlou** [comment]
Every test output file is being prepended with the following bytes:

```
0500 0500 0001 7f00 0001 2712
```

Which looks like the SOCKS handshake bytes, followed by localhost (`7f00 0001`), then a mysterious 2712 that I can't figure out (port?).

screen shot 2016-10-20 at 3 46 55 pm

**Comment by huumanoid** [comment]
Same error for every test?
It seems you are using old version of proxysocket. Please, run
```shell
npm install huumanoid/proxysocket
```
and run tests again.
Looking forward for results!

**Comment by Miserlou** [comment]
Ah! That works! I don't know why installing from npm rather than from git would change anything.. but okay!

```
~/Projects/proxysocket-test $ node pipes/sync-test.js 
2/249
3/249
[ .. ]
249/249
checks passed successfully
```
screen shot 2016-10-20 at 5 07 57 pm

So, this is good news. Next is to check how it figures into the upstream application..

**Comment by huumanoid** [comment]
Hello @Miserlou and thank you for staying with us.

I think i have good news for you!
Sorry, my tests are bad. They were created in effort to avoid encoding bug fix, but it's no way.
Try to install
```shell
npm install huumanoid/proxysocket#encoding
```
You can install this patch without needing changes in your code, in case:
1. You assume that socket provides you buffer in `data` event, and you are decoding buffers manually, if needed.
2. You are not using `socket.setEncoding('binary')` to force socket to interpret received data as binary data.

Hope, your app would work as expected. Looking forward for news from you.

**Comment by Miserlou** [comment]
It works! It freaking works! I could kiss you!

screen shot 2016-10-21 at 3 56 04 pm

A million thanks and many more, you sweet, blessed angel of open-source software.

**Comment by krisives** [comment]
Hey guys. Sorry I haven't been as active as I want in this project, I'm running a lot of stuff right now (asmcup project on top of my regular projects).  Again I wish I had more time available right now, but I am positive I will be using SOCKS5 proxy with node again sometime soon.

Big thanks to both of you for helping with proxysocket.

Should I go ahead and merge this and update NPM?

**Comment by Miserlou** [comment]
The "working" version is in @huumanoid's `encoding` branch, which is currently outside of this PR. 

I also think that it'd be great if the test suite here: https://github.com/HuuMaNoID/proxysocket-test could be merged into the mainline and be made part of a Travis integration for this project. Perhaps that's a longer term goal and a link in the README would suffice for now.

**Comment by huumanoid** [comment]
Thanks @Miserlou I'm glad to hear such compliments from you!

@krisives glad to see you are following our conversation!
I need some time to investigate does my changes in `encoding` branch breaks backward compatibility and add this important changes in this pull request. Seems like without fixing encoding issue proxysocket is useless for binary data.

**Comment by huumanoid** [comment]
I think it's ready to merge.

**Comment by Miserlou** [comment]
Hooray! Can you please publish this to NPM?! 😃

**Comment by krisives** [comment]
NPM has been udpated :grinning:

**Comment by Miserlou** [comment]
RAWK! Thank you to everybody involved in this one!

**Pull request merged**
